/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef graphwrite_CONSTANTS_H
#define graphwrite_CONSTANTS_H

#include "graphwrite_types.h"



class graphwriteConstants {
 public:
  graphwriteConstants();

};

extern const graphwriteConstants g_graphwrite_constants;



#endif
