// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "GraphWrite.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

class GraphWriteHandler : virtual public GraphWriteIf {
 public:
  GraphWriteHandler() {
    // Your initialization goes here
  }

  int64_t addEdge(const int64_t id1, const int64_t id2) {
    // Your implementation goes here
    printf("addEdge\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<GraphWriteHandler> handler(new GraphWriteHandler());
  shared_ptr<TProcessor> processor(new GraphWriteProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

