/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "graphwrite_constants.h"



const graphwriteConstants g_graphwrite_constants;

graphwriteConstants::graphwriteConstants() {
}



